plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.11'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.cyclonedx.bom' version '1.8.2'
    id 'org.spdx.sbom' version '0.7.0'
    id 'org.owasp.dependencycheck' version '9.0.9'
}

group = 'com.finss'
version = '0.0.1-SNAPSHOT'
description = 'backend'


sourceCompatibility = '17'
targetCompatibility = '17'

// java {
//     toolchain {
//         languageVersion = JavaLanguageVersion.of(17)
//     }
// }

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    all {
        resolutionStrategy {
            force 'org.apache.tomcat.embed:tomcat-embed-core:10.1.55'
            force 'org.apache.tomcat.embed:tomcat-embed-el:10.1.55'
            force 'org.apache.tomcat.embed:tomcat-embed-websocket:10.1.55'
            force 'org.springframework:spring-webmvc:6.1.14'
            force 'org.springframework:spring-web:6.1.14'
            force 'org.springframework:spring-core:6.1.14'
            force 'org.springframework:spring-context:6.1.14'
            force 'org.springframework.security:spring-security-web:6.3.4'
            force 'org.springframework.security:spring-security-core:6.3.4'
            force 'org.springframework.security:spring-security-crypto:6.3.8'
            force 'com.fasterxml.jackson.core:jackson-databind:2.18.8'
            force 'com.fasterxml.jackson.core:jackson-core:2.18.8'
            force 'ch.qos.logback:logback-core:1.5.13'
            force 'ch.qos.logback:logback-classic:1.5.13'
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {


    implementation 'org.springframework.boot:spring-boot-starter-web'
    // Security 추가
    implementation 'org.springframework.boot:spring-boot-starter-security'
    // DB 테이블 - Java Entity 자동 매핑 / CRUD 코드 최소화, Spring Data JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    //어노테이션 사용
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    runtimeOnly 'com.mysql:mysql-connector-j'
    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

dependencyCheck {
       autoUpdate = false        // 인터넷 접속 차단
       failOnError = false       // 분석 실패해도 빌드는 성공시킴 (결과 확인용)
       format = 'JSON'           // 우리가 필요한 JSON 형식
   }

tasks.named('test') {
    useJUnitPlatform()
}
tasks.named('jar') {
    enabled = false
}