//API TEST CODE
### Register User
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "username": "test_user1",
  "password": "12341234",
  "email": "test_user11@example.com"
}
