//API TEST CODE
### Register User
POST http://localhost:8080/api/users/register
Content-Type: application/json

{
  "username": "test_user_intelliJj",
  "password": "password1233",
  "email": "test_intellij@examplee.com"
}
